In [2]:
!pip install chardet
#!pip install pandas
#!pip install --upgrade pip

Collecting chardet
  Using cached chardet-7.4.3-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (886 kB)
Installing collected packages: chardet
Successfully installed chardet-7.4.3

In [3]:
import pandas as pd 
import os
import chardet
import glob

In [15]:
os.getcwd()

'/home/rstudio/data-coration-eLTER/data-analysis'

In [16]:
#hier je nach dem Pfad ändern !!!
base = "/home/rstudio/"

filepaths = {
    "data": [
        f"{base}data-coration-eLTER/datasets_by_ID/Italy/Matschertal-Val-di-Mazia-Italy/1t6bq-fre69/IT_Mazia-Matsch-LTER_SOBIO_017_lichen_DATA-2017.csv",
        f"{base}data-coration-eLTER/datasets_by_ID/Italy/Matschertal-Val-di-Mazia-Italy/1t6bq-fre69/IT_Mazia-Matsch-LTER_SOBIO_017_mosses_DATA-2017.csv",
        f"{base}data-coration-eLTER/datasets_by_ID/Italy/Matschertal-Val-di-Mazia-Italy/1t6bq-fre69/IT_Mazia-Matsch-LTER_SOBIO_017_veg_DATA-2017.csv",
    
    ],
    #"data": f"{base}data-coration-eLTER/datasets_by_ID/Italy/Matschertal-Val-di-Mazia-Italy/1t6bq-fre69/IT_Mazia-Matsch-LTER_SOBIO_017_lichen_DATA-2017.csv",
    "method": f"{base}data-coration-eLTER/datasets_by_ID/Italy/Matschertal-Val-di-Mazia-Italy/1t6bq-fre69/IT_Mazia-Matsch-LTER_SOBIO_017_lichen-mosses-veg_METHOD-2017.csv",
    "station": f"{base}data-coration-eLTER/datasets_by_ID/Italy/Matschertal-Val-di-Mazia-Italy/1t6bq-fre69/IT_Mazia-Matsch_LTER_SOBIO_017_lichen-mosses-veg_STATION-2017.csv",
    #"reference": f"{base}data-coration-eLTER/datasets_by_ID/Italy/Matschertal-Val-di-Mazia-Italy/3jaen-02038/IT_ValMazia-Matschertal_METEO_2023-2024_V20251029_reference.csv",
    #"license": f"{base}data-coration-eLTER/datasets_by_ID/Italy/Matschertal-Val-di-Mazia-Italy/3jaen-02038/IT_ValMazia-Matschertal_METEO_2023-2024_V20251029_license.txt",
}
# 
#

In [1]:
import psutil
ram = psutil.virtual_memory()
print(f"Gesamt:     {ram.total / 1024**2:.0f} MB")
print(f"Verfügbar:  {ram.available / 1024**2:.0f} MB")
print(f"Verbraucht: {ram.percent}%")

Gesamt:     999609 MB
Verfügbar:  125876 MB
Verbraucht: 87.4%

In [28]:
# copy the path of the data when there is just one data-file
#df_data = pd.read_csv(filepaths["data"], sep=";", low_memory=False, skiprows=11) #, encoding="latin-1",
#df_data.head() 
#if mor than one data-file
df_data = pd.concat([pd.read_csv(p,sep=";", skiprows=11) for p in filepaths["data"]], ignore_index=True)
pd.set_option('display.max_rows', None) 
df_data.head(20)
#df_data.iloc[1000000:1000020]

,SITE_CODE,STATION_CODE,HORI_OFFSET,TIME,LAYER,Alectoria ochroleuca (Hoffm.) A. Massal.,"Athallia pyracea (Ach.) Arup, Frödén & Søchting","Athallia saxifragarum (Poelt) Arup, Frödén & Søchting",Bryonora castanea (Hepp) Poelt,"Bryoplaca sinapisperma (DC.) Søchting, Frödén & Arup",...,Trifolium pratense,Ulmus pumila,Verbascum lychnitis,Veronica bellidioides,Veronica chamaedrys,Veronica fruticans,Veronica spicata,Viola canina,Viola rupestris,Viola sp.
0,https://deims.org/51d0598a-e9e1-4252-8850-60fc8f329aab,1000.1,NaN,2017-06-26,M,0.0,3.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://deims.org/51d0598a-e9e1-4252-8850-60fc8f329aab,1000.2,NaN,2018-06-26,M,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://deims.org/51d0598a-e9e1-4252-8850-60fc8f329aab,1000.3,NaN,2019-06-26,M,0.0,2.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://deims.org/51d0598a-e9e1-4252-8850-60fc8f329aab,1500.1,NaN,2020-06-26,M,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://deims.org/51d0598a-e9e1-4252-8850-60fc8f329aab,1500.2,NaN,2021-06-26,M,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,https://deims.org/51d0598a-e9e1-4252-8850-60fc8f329aab,1500.3,NaN,2022-06-26,M,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,https://deims.org/51d0598a-e9e1-4252-8850-60fc8f329aab,2000.1,NaN,2017-06-27,M,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,https://deims.org/51d0598a-e9e1-4252-8850-60fc8f329aab,2000.2,NaN,2018-06-27,M,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,https://deims.org/51d0598a-e9e1-4252-8850-60fc8f329aab,2000.3,NaN,2019-06-27,M,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,https://deims.org/51d0598a-e9e1-4252-8850-60fc8f329aab,2500.1,NaN,2020-06-27,M,1.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,https://deims.org/51d0598a-e9e1-4252-8850-60fc8f329aab,2500.2,NaN,2021-06-27,M,0.0,0.0,0.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,https://deims.org/51d0598a-e9e1-4252-8850-60fc8f329aab,2500.3,NaN,2022-06-27,M,0.0,0.0,1.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,https://deims.org/51d0598a-e9e1-4252-8850-60fc8f329aab,1000.1,NaN,2017-06-26,M,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,https://deims.org/51d0598a-e9e1-4252-8850-60fc8f329aab,1000.2,NaN,2018-06-26,M,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,https://deims.org/51d0598a-e9e1-4252-8850-60fc8f329aab,1000.3,NaN,2019-06-26,M,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,https://deims.org/51d0598a-e9e1-4252-8850-60fc8f329aab,1500.1,NaN,2020-06-26,M,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,https://deims.org/51d0598a-e9e1-4252-8850-60fc8f329aab,1500.2,NaN,2021-06-26,M,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,https://deims.org/51d0598a-e9e1-4252-8850-60fc8f329aab,1500.3,NaN,2022-06-26,M,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,https://deims.org/51d0598a-e9e1-4252-8850-60fc8f329aab,2000.1,NaN,2017-06-27,M,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,https://deims.org/51d0598a-e9e1-4252-8850-60fc8f329aab,2000.2,NaN,2018-06-27,M,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
# check if you g´have to skiprows = ..x..
with open(filepaths["data"], "r") as f:
    for i, line in enumerate(f):
        print(i, line)
        if i > 10:
            break

TypeError: unhashable type: 'list'

In [26]:
# path of metode for just one method
df_method = pd.read_csv(filepaths["method"], sep=";", skiprows=8)
pd.set_option('display.max_rows', None) # make sure every one is shown (method is not so huge)
pd.set_option('display.max_colwidth', None) 
#display(df_method)
df_method.head(20)

,VARIABLE,METH_DESCR,SAMPLING_DESIGN,FIELD_METHOD
0,Spec_pres,"A circular plot with a radius of 13 m was centered on the georeferenced point. Within the plot, five subplots measuring 50 × 40 cm were placed, where terrestrial lichen and bryophyte communities were recorded (presence/absence in each subplot). Within five 3 × 3 m subplots, surrounding the lichen/bryophyte subplots, vascular plant communities were recorded.",The plots were surveyed during a sampling campaign in 2017 to collect data on pastures already sampled in 2016.,"In total, 12 pasture plots were sampled along an altitudinal gradient. We saved the data on lichen, bryophytes and lichens in three different csv files."

In [12]:
# copy the path of station 
df_station =pd.read_csv(filepaths["station"], sep=",", skiprows=0)
display(df_station.head())

,SITE_CODE,STATION_CODE,STYPE,LON,LAT,ALTITUDE,PLOTSIZE
0,https://deims.org/51d0598a-e9e1-4252-8850-60fc8f329aab,b1,AREA,46.661183,10.590244,983,203
1,https://deims.org/51d0598a-e9e1-4252-8850-60fc8f329aab,b2,AREA,46.686253,10.579917,1473,325
2,https://deims.org/51d0598a-e9e1-4252-8850-60fc8f329aab,p2,AREA,46.684306,10.585125,1541,49
3,https://deims.org/51d0598a-e9e1-4252-8850-60fc8f329aab,b3,AREA,46.691694,10.591936,1922,124
4,https://deims.org/51d0598a-e9e1-4252-8850-60fc8f329aab,s4,AREA,46.706981,10.602181,2404,20

In [13]:
with open(filepaths["license"], "r") as f:
    print(f.read())

CC-BY-4.0-INT

In [29]:
df_reference =  pd.read_csv(filepaths["reference"])
display(df_reference)

KeyError: 'reference'

In [32]:
# file names
print("-" * 55)
print("FILE INFO")
print("-" * 55)

base = "/home/rstudio/"

pfad = f"{base}data-coration-eLTER/datasets_by_ID/Italy/Matschertal-Val-di-Mazia-Italy/1t6bq-fre69"

# parent folders
print(f"parent folders: {os.path.basename(pfad)}")
# subfiles
print("\nSubfiles:")
for datei in os.listdir(pfad):
    print(f"  - {datei}")

# data volume
print("-" * 55)
print("data volume")
print("-" * 55)

#pfad = f"{base}data-coration-eLTER/datasets_by_ID/Italy/Matschertal-Val-di-Mazia-Italy/1t6bq-fre69/IT_Mazia-Matsch-LTER_SOBIO_017_veg_DATA-2017.csv"



#total = os.path.getsize(pfad)
#print(f"Dateigröße: {total} bytes")

total = 0
for f in os.listdir(pfad):
    fp = os.path.join(pfad, f)
    if os.path.isfile(fp):
        total += os.path.getsize(fp)

print(f"File size: {total / (1024 * 1024):.2f} MB")

# wide- or long format, if "variable" => long, "var1", "var2".. => wide & number of rows and columns
print("\n" + "-" * 55)
print("STRUCTURE")
print("-" * 55)

#print(f"Columns:  {df_data.columns.tolist()}")
print(f"Num columns: {len(df_data.columns)}")
print(f"Rows:     {len(df_data)}")
print(f"Format:   {'Long' if 'VARIABLE' in df_data.columns else 'Wide'}")

# temporal coverage
print("\n" + "-" * 55)
print("TEMPORAL COVERAGE")
print("-" * 55)

df_data['TIME'] = pd.to_datetime(df_data['TIME'], errors='coerce')
df_valid = df_data.dropna(subset=['TIME', "LAYER"])
print(f"Form:        {df_valid['TIME'].min()}")
print(f"to:        {df_valid['TIME'].max()}")

# temporal resolution 
print("\n" + "-" * 55)
print("TEMPORAL RESOLUTION")
print("-" * 55)

print(f"Median interval:  {df_valid['TIME'].diff().median()}")
#summary = df_data.groupby('VARIABLE', group_keys=False).apply(
    #lambda g: pd.Series({
        #'n':      len(g),
        #'median': g.sort_values('TIME')['TIME'].drop_duplicates().diff().median(),  # ← drop_duplicates
        #'min':    g.sort_values('time')['time'].drop_duplicates().diff().dropna().min(),
        #'max':    g.sort_values('time')['time'].drop_duplicates().diff().dropna().max(),
        #'from':   g['time'].min().strftime('%Y-%d-%m'),
        #'to':     g['time'].max().strftime('%Y-%d-%m'),
    #}),
    #include_groups=False  # ← FutureWarning fix
#)
#print(summary)

#File encoding 06.
print("\n" + "-" * 55)
print("File encoding 06")
print("-" * 55)

#encoding if all are strings:

#for name, path in filepaths.items():
#    with open(path, "rb") as f:
#        result = chardet.detect(f.read())
#        print(f"{name}: {result['encoding']}")

#encoding it filepath are strings and list:

for name, paths in filepaths.items():
    # Einheitlich als Liste behandeln
    if isinstance(paths, str):
        paths = [paths]
    for path in paths:
        with open(path, "rb") as f:
            result = chardet.detect(f.read())
            print(f"{name}: {result['encoding']}")

-------------------------------------------------------
FILE INFO
-------------------------------------------------------
parent folders: 1t6bq-fre69

Subfiles:
  - IT_Mazia-Matsch-LTER_SOBIO_017_lichen_DATA-2017.csv
  - IT_Mazia-Matsch-LTER_SOBIO_017_lichen-mosses-veg_METHOD-2017.csv
  - IT_Mazia-Matsch_LTER_SOBIO_017_lichen-mosses-veg_STATION-2017.csv
  - IT_Mazia-Matsch-LTER_SOBIO_017_mosses_DATA-2017.csv
  - IT_Mazia-Matsch-LTER_SOBIO_017_veg_DATA-2017.csv
-------------------------------------------------------
data volume
-------------------------------------------------------
File size: 0.02 MB

-------------------------------------------------------
STRUCTURE
-------------------------------------------------------
Num columns: 237
Rows:     36
Format:   Wide

-------------------------------------------------------
TEMPORAL COVERAGE
-------------------------------------------------------
Form:        2017-06-26 00:00:00
to:        2022-06-27 00:00:00

-------------------------------------------------------
TEMPORAL RESOLUTION
-------------------------------------------------------
Median interval:  365 days 00:00:00

-------------------------------------------------------
File encoding 06
-------------------------------------------------------
data: UTF-8-SIG
data: UTF-8-SIG
data: UTF-8-SIG
method: UTF-8-SIG
station: UTF-8-SIG